name: CI

on: [push]

jobs:  
  test_artifact:
    name: tests for artifact
    runs-on: ubuntu-latest

    steps:
      - name: Install pip dependencies
        run: pip3 install mypy
      - name: Run static analyzer
        working-directory: ./artifact/
        run: mypy -h
      - name: Run unittest
        working-directory: ./artifact/
        run: python3 -m unittest
      
  test_run:
    name: tests for run
    runs-on: ubuntu-latest

    steps:
      - name: Install pip dependencies
        run: pip3 install mypy
      - name: Run unittest
        working-directory: ./run/
        run: python3 -m unittest
      - name: Run static analyzer
        working-directory: ./run/
        run: mypy -p gem5art.run
      
  test_tasks:
    name: tests for tasks
    runs-on: ubuntu-latest

    steps:
      - name: Install pip dependencies
        run: pip3 install mypy
      - name: Run static analyzer
        working-directory: ./tasks/
        run: mypy -p gem5art.tasks
      - name: Run unittest
        working-directory: ./tasks/
        run: python3 -m unittest
